/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ittufwcrotfyklykdgwk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dHVmd2Nyb3RmeWtseWtkZ3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzOTkyMjksImV4cCI6MjA5MDk3NTIyOX0.y1MwzcYLXFazbsc50eVCRdq-Sd-GXVeHdqTS31XUDsA"