import React, { createContext, useContext, ReactNode } from 'react';
import { useParams, useNavigate } from 'react-router';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Page Titles
    'page.title.home': 'Luuzon - trust in rental, restored',
    'page.title.manifesto': 'Manifesto - Luuzon',
    'page.title.privacy': 'Privacy Policy - Luuzon',
    'page.title.legal': 'Legal Notice - Luuzon',
    
    // Hero Section
    'hero.badge': 'Private Beta Live',
    'hero.title1': 'Trust in rentals,',
    'hero.title2': 'restored.',
    'hero.subtitle': 'The institutional standard for lease verification. We connect verified agencies with honest tenants through an intelligent, neutral B2B2C ecosystem.',
    'hero.cta': 'Book a demo',
    'hero.topBanner': 'We are transforming the rental market.',
    'hero.topBannerButton': 'Join Beta',
    
    // Navigation
    'nav.manifesto': 'Read Manifesto',
    'nav.product': 'Product',
    'nav.whyNow': 'Why Now',
    'nav.howItWorks': 'How it works',
    
    // Our Promise
    'promise.badge': 'Why Luuzon',
    'promise.title1': 'One application.',
    'promise.title2': 'Infinite possibilities.',
    'promise.intro': 'In a time when every lease feels like a gamble, when agencies drown in paperwork and tenants fear for their deposits, we have lost the trust that makes a home.',
    'promise.subtitle': 'We believe renting should be transparent, fair, and frictionless. Your verified profile travels with you—apply once, rent anywhere.',
    'promise.market.broken': 'The market is broken. Agencies are overwhelmed by manual checks and fraud risks. Honest tenants struggle with opaque processes.',
    'promise.bridge': 'Luuzon is the bridge. An intelligent CRM for professionals, and a verified passport for tenants.',
    'promise.feature1.title': 'AI-Powered Verification',
    'promise.feature1.desc': 'Instant document analysis detects fraud and validates authenticity in seconds, not days.',
    'promise.feature2.title': 'Portable Trust Score',
    'promise.feature2.desc': 'Build your rental reputation once. Carry it everywhere. Never start from scratch again.',
    'promise.feature3.title': 'Privacy First',
    'promise.feature3.desc': 'Your data stays encrypted and under your control. Share only what is needed, when it is needed.',
    
    // Alumni
    'alumni.title': 'Built by alumni of',
    
    // Fraud Detection Demo
    'fraud.badge': 'Live Demo',
    'fraud.title1': 'Watch AI Detect Fraud',
    'fraud.title2': 'In Real-Time',
    'fraud.subtitle': 'See how our AI analyzes a sample tenant application, detecting manipulated documents and scoring applicant risk.',
    'fraud.randomNote': 'Results are randomised on every run.',
    'fraud.runButton': 'Run Analysis',
    'fraud.analyzing': 'Analyzing...',
    'fraud.analysisComplete': 'Analysis Complete',
    'fraud.trustScore': 'Trust Score',
    'fraud.documentVerification': 'Document Verification',
    'fraud.flagsDetected': 'flags detected',
    'fraud.allVerified': 'All verified',
    'fraud.verified': 'Verified',
    'fraud.flagged': 'Flagged',
    'fraud.warning': 'Warning',
    'fraud.scanning': 'Scanning',
    'fraud.pending': 'Pending',
    'fraud.riskAssessment': 'Risk Assessment',
    'fraud.riskLevel': 'Risk Level',
    'fraud.low': 'Low',
    'fraud.medium': 'Medium',
    'fraud.high': 'High',
    'fraud.recommendation': 'Recommendation',
    'fraud.recommendApprove': 'Approve with confidence',
    'fraud.recommendReview': 'Manual review recommended',
    'fraud.recommendReject': 'High risk - additional verification required',
    'fraud.income': 'Income',
    'fraud.identity': 'Identity',
    'fraud.employment': 'Employment',
    'fraud.ok': 'OK',
    'fraud.flag': 'Flag',
    'fraud.reject': 'Reject',
    'fraud.confidence': 'Confidence',
    'fraud.documentsAnalyzed': 'Documents Analyzed',
    'fraud.analysisTime': 'Analysis Time',
    'fraud.warningsFound': 'Warnings Found',
    'fraud.progress': 'Progress',
    'fraud.timeline': 'Timeline',
    'fraud.uploadedDocuments': 'Uploaded Documents',
    'fraud.applicant': 'Applicant',
    'fraud.analysisResults': 'Analysis Results',
    'fraud.upload': 'Upload',
    'fraud.analyze': 'Analyze',
    'fraud.review': 'Review',
    'fraud.done': 'Done',
    'fraud.uploaded': 'Uploaded',
    'fraud.analyzing2': 'Analyzing',
    'fraud.review2': 'Review',
    'fraud.completed': 'Completed',
    'fraud.documentsReceived': 'Documents received',
    'fraud.aiVerificationInProgress': 'AI verification in progress',
    'fraud.resultsUnderReview': 'Results under review',
    'fraud.analysisFinalized': 'Analysis finalized',
    'fraud.scan': 'Scan',

    // EN — à ajouter dans la section fraud
    'fraud.doc1.name': 'Payslip_March_2024.pdf',
    'fraud.doc1.meta': '240 KB • INCOME PROOF',
    'fraud.doc2.name': 'ID_Card_Front.jpg',
    'fraud.doc2.meta': '1.2 MB • IDENTITY DOCUMENT',
    'fraud.doc3.name': 'Employment_Reference.pdf',
    'fraud.doc3.meta': '180 KB • EMPLOYMENT',

    // Outcomes doc 1 (payslip)
    'fraud.doc1.out0': 'Employer match confirmed. Income amount consistent with market rate.',
    'fraud.doc1.out1': 'Income verified. Minor formatting anomaly detected — likely benign.',
    'fraud.doc1.out2': 'Payslip authentic. Employer NIF cross-referenced successfully.',
    'fraud.doc1.out3': 'Salary figure inconsistent with declared employer size. Manual review advised.',
    'fraud.doc1.out4': 'Possible document tampering — font metrics inconsistent on salary field.',
    'fraud.doc1.out5': 'Metadata shows file was edited 3 days after stated issue date. High risk.',

    // Outcomes doc 2 (ID)
    'fraud.doc2.out0': 'MRZ code valid. Portrait biometrics pass liveness check.',
    'fraud.doc2.out1': 'Identity confirmed. Document expiry within acceptable range.',
    'fraud.doc2.out2': 'Low resolution scan. Expiry date approaching in 6 weeks.',
    'fraud.doc2.out3': 'Microprint strip blurred — possible photocopy. Request original.',
    'fraud.doc2.out4': 'Face crop inconsistency detected. Lighting artifacts around portrait edge.',
    'fraud.doc2.out5': 'Document security features absent. High probability of forgery.',

    // Outcomes doc 3 (employment)
    'fraud.doc3.out0': 'Employment dates confirmed. Digital signature cryptographically valid.',
    'fraud.doc3.out1': 'Employer verified against business registry. Contract terms consistent.',
    'fraud.doc3.out2': 'Reference letter authentic. Employer contact details verified.',
    'fraud.doc3.out3': 'Signatory not found in company directory. Possible third-party issuer.',
    'fraud.doc3.out4': 'Employment gap of 4 months unaddressed. Start date discrepancy vs. CV.',
    'fraud.doc3.out5': 'Company registration number does not exist in national registry. Fraudulent.',

    'fraud.doc.income': 'Income',
    'fraud.doc.identity': 'Identity',
    'fraud.doc.employment': 'Employment',
    'fraud.trustLabel.excellent': 'Excellent',
    'fraud.trustLabel.good': 'Good',
    'fraud.trustLabel.moderate': 'Moderate',
    'fraud.trustLabel.poor': 'Poor',
    'fraud.trustLabel.highRisk': 'High Risk',
    
    // How It Works
    'howItWorks.badge': 'Process',
    'howItWorks.title1': 'From application to approval',
    'howItWorks.title2': 'in seconds.',
    'howItWorks.subtitle': 'Automate the heavy lifting. We handle the data, verification, and scoring so you can focus on the decision.',
    'howItWorks.step1.title': 'Upload Documents',
    'howItWorks.step1.desc': 'Tenants upload their ID, payslips, and tax forms in seconds. No more email chains or lost PDFs.',
    'howItWorks.step2.title': 'AI Analysis',
    'howItWorks.step2.desc': 'Our engine reads, verifies, and cross-checks data against fraud patterns instantly.',
    'howItWorks.step3.title': 'Get Results',
    'howItWorks.step3.desc': 'Receive a complete risk score, red flags, and verified tenant profile ready for decision.',
    'howItWorks.stat1.value': '< 30s',
    'howItWorks.stat1.label': 'Analysis Time',
    'howItWorks.stat2.value': '99.7%',
    'howItWorks.stat2.label': 'Fraud Detection',
    'howItWorks.stat3.value': '45min',
    'howItWorks.stat3.label': 'Time Saved',
    'howItWorks.stat4.value': '0hr',
    'howItWorks.stat4.label': 'Manual PDF Reading',
    
    // Testimonial
    'testimonial.quote': 'We built the intelligent CRM that agencies needed.',
    'testimonial.subtext': 'But we didn\'t stop there. Every verified tenant deserves a passport—a portable proof of trust that follows them from one home to the next.',
    
    // Passport Demo
    'passport.badge': 'Live Interactive Demo',
    'passport.title1': 'Shareable.',
    'passport.title2': 'Encrypted.',
    'passport.title3': 'Privacy-First.',
    'passport.subtitle': 'Generate a secure public link that agencies can view without an account. Only verified status is shown — never your sensitive data.',
    'passport.headerPrivate': 'Your Private Passport Dashboard',
    'passport.headerPublic': 'Agency View (No Login Required)',
    'passport.encrypted': 'End-to-End Encrypted',
    'passport.fullPassport': 'Your Full Passport',
    'passport.publicView': 'Public Passport View',
    'passport.private': 'Private',
    'passport.public': 'Public',
    'passport.verifiedSince': 'Verified since March 2024',
    'passport.identityStatus': 'Identity Status',
    'passport.verified': 'Verified ✓',
    'passport.fullName': 'Full Name',
    'passport.incomeBracket': 'Income Bracket',
    'passport.exactSalary': 'Exact Salary',
    'passport.employmentStatus': 'Employment Status',
    'passport.employmentCDI': 'CDI (Permanent)',
    'passport.employerName': 'Employer Name',
    'passport.rentalHistory': 'Rental History',
    'passport.rentalHistoryValue': '3+ years, No Issues',
    'passport.previousAddresses': 'Previous Addresses',
    'passport.trustScore': 'Trust Score',
    'passport.trustScoreValue': '98/100',
    'passport.fraudCheck': 'AI Fraud Check',
    'passport.fraudCheckPassed': 'Passed ✓',
    'passport.hidden': 'Hidden',
    'passport.shareTitle': 'Share Your Passport',
    'passport.whatAgenciesSee': 'What Agencies See',
    'passport.privacyProtected': 'Privacy Protected',
    'passport.privacyDesc': 'Your public link only shows verified status, never actual documents or sensitive data.',
    'passport.publiclyVisible': 'PUBLICLY VISIBLE',
    'passport.alwaysHidden': 'ALWAYS HIDDEN',
    'passport.publicItem1': 'Identity ✓',
    'passport.publicItem2': 'Income Range',
    'passport.publicItem3': 'Employment Type',
    'passport.publicItem4': 'Rental History',
    'passport.publicItem5': 'Trust Score',
    'passport.publicItem6': 'Fraud Check ✓',
    'passport.hiddenItem1': 'Full Name',
    'passport.hiddenItem2': 'Exact Salary',
    'passport.hiddenItem3': 'Employer',
    'passport.hiddenItem4': 'Addresses',
    'passport.hiddenItem5': 'Documents',
    'passport.generateLink': 'Generate Shareable Link',
    'passport.generating': 'Generating encrypted link...',
    'passport.yourLink': 'Your Passport Link',
    'passport.copy': 'Copy',
    'passport.copied': 'Copied',
    'passport.linkDescription': 'Anyone with this link can view your verified status — no account needed',
    'passport.tenantVerified': 'Tenant Verified',
    'passport.cryptoVerified': 'This passport has been cryptographically verified by Luuzon AI.',
    'passport.quickSummary': 'Quick Summary',
    'passport.income': 'Income',
    'passport.employment': 'Employment',
    'passport.history': 'History',
    'passport.fullDetailsAvailable': 'Full Details Available',
    'passport.fullDetailsDesc': 'Request full access through Luuzon to see complete documents with tenant consent.',
    'passport.restartDemo': 'Restart Demo',
    'passport.feature1': 'No Account Required',
    'passport.feature1Desc': 'Agencies view instantly',
    'passport.feature2': 'Zero Sensitive Data',
    'passport.feature2Desc': 'Only verification status',
    'passport.feature3': 'Cryptographic Proof',
    'passport.feature3Desc': 'Tamper-proof verification',
    
    // FAQ
    'faq.badge': 'FAQ',
    'faq.title': 'Questions? We have answers.',
    'faq.q1': 'How does AI detect fraud?',
    'faq.a1': 'Our AI analyzes documents for inconsistencies, metadata anomalies, font irregularities, and cross-references data points against known fraud patterns. It\'s trained on millions of verified and fraudulent documents.',
    'faq.q2': 'Is my data secure?',
    'faq.a2': 'Absolutely. We use bank-grade encryption, zero-knowledge architecture, and comply with GDPR. You control what data is shared and with whom. We never sell your information.',
    'faq.q3': 'How long does verification take?',
    'faq.a3': 'Most verifications complete in under 30 seconds. Complex cases requiring manual review may take up to 24 hours, but this represents less than 2% of applications.',
    'faq.q4': 'Can I use this across multiple agencies?',
    'faq.a4': 'Yes! That\'s the entire point. Build your verified profile once, then apply to any agency or property on our network with a single click. Your trust score travels with you.',
    'faq.q5': 'What happens if a document is flagged?',
    'faq.a5': 'Flagged documents enter manual review by our verification team. You\'ll be notified and given the opportunity to submit corrected documents. False positives are rare but handled with care.',
    'faq.subtitle': 'For Agencies & Tenants',
    'faq.heading': 'Frequently Asked Questions',
    'faq.question1': 'How does Luuzon protect my personal data?',
    'faq.answer1': 'We use bank-grade encryption (AES-256) and strictly adhere to GDPR. Your data is encrypted at rest and in transit. Crucially, agencies only see your verified status unless you explicitly grant full access.',
    'faq.question2': 'What happens if there is a data breach?',
    'faq.answer2': 'Our decentralized architecture ensures that even in the unlikely event of a breach, attackers would only find fragmented, encrypted shards that are useless without your private key.',
    'faq.question3': 'How much does Luuzon cost for agencies?',
    'faq.answer3': 'We offer flexible pricing tiers starting with a free usage tier. Enterprise plans include API access and bulk verification discounts.',
    'faq.question4': 'Is Luuzon free for tenants?',
    'faq.answer4': 'Yes! Tenants can create a Verified Passport for free. We believe proving your trustworthiness shouldn\'t cost you money.',
    'faq.question5': 'How does the AI verification process work?',
    'faq.answer5': 'Our proprietary AI analyzes document metadata, cross-references income with bank statements, and checks global fraud databases instantly.',
    'faq.question6': 'How long does verification take?',
    'faq.answer6': 'Typically under 30 seconds. In rare complex cases, a manual review might take up to 2 hours.',
    'faq.question7': 'What if the AI flags my documents incorrectly?',
    'faq.answer7': 'You can request a manual review immediately. Our human compliance team will re-evaluate your documents within 24 hours.',
    'faq.question8': 'Can agencies see my full documents?',
    'faq.answer8': 'By default, no. They see a \'Verified\' status. You can choose to share the actual files if required for the final lease signing.',
    'faq.moreQuestions': 'More questions?',
    'faq.contactUs': 'Contact Us',
    
    // Footer
    'footer.title': 'You don\'t have to do this alone',
    'footer.support': 'Support',
    'footer.manifesto': 'Read our Manifesto',
    'footer.contact': 'Contact a founder',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.copyright': '© Luuzon 2026',
    
    // Cookies
    'cookies.title': 'We value your privacy',
    'cookies.description': 'We use cookies to enhance your browsing experience and analyze our traffic. You can choose which types of cookies you allow.',
    'cookies.essential': 'Essential',
    'cookies.essentialDesc': 'Required for the website to function',
    'cookies.analytics': 'Analytics',
    'cookies.analyticsDesc': 'Help us improve our service',
    'cookies.marketing': 'Marketing',
    'cookies.marketingDesc': 'Used for targeted advertising',
    'cookies.acceptAll': 'Accept All',
    'cookies.rejectAll': 'Reject All',
    'cookies.configure': 'Configure',
    'cookies.savePreferences': 'Save Preferences',
    'cookies.backToMain': 'Back',
    
    // Manifesto
    'manifesto.badge': 'Manifesto',
    'manifesto.hero.title1': 'Housing, Automated.',
    'manifesto.hero.title2': 'Living, Simplified.',
    'manifesto.section1.number': '01 — Our Philosophy',
    'manifesto.section1.title': 'Trust is the foundation of every home',
    'manifesto.section1.p1': 'The rental market is broken. It is a tangle of inefficiencies, mistrust, and outdated processes that frustrate tenants and burden agencies alike.',
    'manifesto.section1.p2': 'We believe in a world where renting is transparent, dignified, and frictionless. Where your reputation travels with you. Where trust is not assumed—it\'s verified.',
    'manifesto.section1.p3': 'This is not just about technology; it\'s about restoring humanity to housing. It\'s about building systems that respect both landlords and tenants, creating a market where honesty is rewarded and fraud is impossible.',
    'manifesto.section2.number': '02 — Why Now',
    'manifesto.section2.title': 'The moment for change has arrived',
    'manifesto.section2.p1': 'Fraud is rising. Agencies are overwhelmed. Tenants spend weeks proving their credibility with mountains of paperwork. The current system wastes time, money, and trust.',
    'manifesto.section2.p2': 'Meanwhile, AI has reached an inflection point. What once required armies of analysts can now be done instantly, accurately, and at scale. The tools exist. The need is urgent. The opportunity is now.',
    'manifesto.section2.p3': 'We are at the intersection of crisis and capability—and that is where transformation happens.',
    'manifesto.section3.number': '03 — Our Solution',
    'manifesto.section3.title': 'An intelligent ecosystem for verified living',
    'manifesto.section3.p1': 'We are building the institutional standard for lease verification—a neutral B2B2C platform that connects verified agencies with honest tenants through AI-powered trust infrastructure.',
    'manifesto.section3.p2': 'Our system instantly verifies documents, detects fraud, and builds portable tenant reputations. One application. One profile. Infinite opportunities.',
    'manifesto.section3.p3': 'Agencies save time and reduce risk. Tenants apply faster and rent with confidence. Landlords welcome vetted residents. Everyone wins when the system works.',
    'manifesto.section4.number': '04 — Our Vision',
    'manifesto.section4.title': 'Your rental history as your passport',
    'manifesto.section4.p1': 'Imagine a world where applying for a home is as simple as a single click. Where your verified history opens doors instead of forcing you to prove yourself again and again.',
    'manifesto.section4.p2': 'We envision a future where housing is accessible, fair, and transparent. Where data empowers rather than exploits. Where privacy and verification coexist.',
    'manifesto.section4.p3': 'We are not just building software—we are redesigning the foundation of how we live. Join us as we make renting work for everyone.',
    'manifesto.closing': 'Welcome to the future of renting',
  },
  fr: {
    // Page Titles
    'page.title.home': 'Luuzon - La confiance en location, restaurée',
    'page.title.manifesto': 'Manifeste - Luuzon',
    'page.title.privacy': 'Politique de Confidentialité - Luuzon',
    'page.title.legal': 'Mentions Légales - Luuzon',
    
    // Hero Section
    'hero.badge': 'Bêta Privée en Cours',
    'hero.title1': 'La confiance en location,',
    'hero.title2': 'restaurée.',
    'hero.subtitle': 'La norme institutionnelle pour la vérification de bail. Nous connectons des agences vérifiées avec des locataires honnêtes via un écosystème B2B2C intelligent et neutre.',
    'hero.cta': 'Réserver une démo',
    'hero.topBanner': 'Nous transformons le marché locatif.',
    'hero.topBannerButton': 'Rejoindre la Bêta',
    
    // Navigation
    'nav.manifesto': 'Lire le Manifeste',
    'nav.product': 'Produit',
    'nav.whyNow': 'Pourquoi Maintenant',
    'nav.howItWorks': 'Comment ça marche',
    
    // Our Promise
    'promise.badge': 'Pourquoi Luuzon',
    'promise.title1': 'Une seule candidature.',
    'promise.title2': 'Possibilités infinies.',
    'promise.intro': 'À une époque où chaque bail ressemble à un pari, où les agences se noient dans la paperasse et où les locataires craignent pour leur dépôt, nous avons perdu la confiance qui fait un foyer.',
    'promise.subtitle': 'Nous croyons que la location devrait être transparente, équitable et sans friction. Votre profil vérifié vous suit partout—postulez une fois, louez n\'importe où.',
    'promise.market.broken': 'Le marché est brisé. Les agences sont submergées par des contrôles manuels et des risques de fraude. Les locataires honnêtes luttent contre des processus opaques.',
    'promise.bridge': 'Luuzon est le pont. Un CRM intelligent pour les professionnels, et un passeport vérifié pour les locataires.',
    'promise.feature1.title': 'Vérification par IA',
    'promise.feature1.desc': 'L\'analyse instantanée des documents détecte la fraude et valide l\'authenticité en quelques secondes, pas en jours.',
    'promise.feature2.title': 'Score de Confiance Portable',
    'promise.feature2.desc': 'Construisez votre réputation locative une fois. Emportez-la partout. Ne recommencez jamais à zéro.',
    'promise.feature3.title': 'Confidentialité d\'Abord',
    'promise.feature3.desc': 'Vos données restent cryptées et sous votre contrôle. Partagez uniquement ce qui est nécessaire, quand c\'est nécessaire.',
    
    // Alumni
    'alumni.title': 'Créé par un alumni de',
    
    // Fraud Detection Demo
    'fraud.badge': 'Démo en Direct',
    'fraud.title1': 'Regardez l\'IA Détecter la Fraude',
    'fraud.title2': 'En Temps Réel',
    'fraud.subtitle': 'Voyez comment notre IA analyse un exemple de candidature locataire, détectant les documents manipulés et évaluant le risque du candidat.',
    'fraud.randomNote': 'Les résultats sont randomisés à chaque exécution.',
    'fraud.runButton': 'Lancer l\'Analyse',
    'fraud.analyzing': 'Analyse en cours...',
    'fraud.analysisComplete': 'Analyse Terminée',
    'fraud.trustScore': 'Score de Confiance',
    'fraud.documentVerification': 'Vérification des Documents',
    'fraud.flagsDetected': 'alertes détectées',
    'fraud.allVerified': 'Tous vérifiés',
    'fraud.verified': 'Vérifié',
    'fraud.flagged': 'Signalé',
    'fraud.warning': 'Attention',
    'fraud.scanning': 'Analyse',
    'fraud.pending': 'En attente',
    'fraud.riskAssessment': 'Évaluation du Risque',
    'fraud.riskLevel': 'Niveau de Risque',
    'fraud.low': 'Faible',
    'fraud.medium': 'Moyen',
    'fraud.high': 'Élevé',
    'fraud.recommendation': 'Recommandation',
    'fraud.recommendApprove': 'Approuver en toute confiance',
    'fraud.recommendReview': 'Examen manuel recommandé',
    'fraud.recommendReject': 'Risque élevé - vérification supplémentaire requise',
    'fraud.income': 'Revenus',
    'fraud.identity': 'Identité',
    'fraud.employment': 'Emploi',
    'fraud.ok': 'OK',
    'fraud.flag': 'Signal',
    'fraud.reject': 'Rejeter',
    'fraud.confidence': 'Confiance',
    'fraud.documentsAnalyzed': 'Documents Analysés',
    'fraud.analysisTime': 'Temps d\'Analyse',
    'fraud.warningsFound': 'Alertes Trouvées',
    'fraud.progress': 'Progression',
    'fraud.timeline': 'Chronologie',
    'fraud.uploadedDocuments': 'Documents Téléchargés',
    'fraud.applicant': 'Candidat',
    'fraud.analysisResults': 'Résultats de l\'Analyse',
    'fraud.upload': 'Télécharger',
    'fraud.analyze': 'Analyser',
    'fraud.review': 'Examiner',
    'fraud.done': 'Terminé',
    'fraud.uploaded': 'Téléchargé',
    'fraud.analyzing2': 'Analyse en cours',
    'fraud.review2': 'Examen',
    'fraud.completed': 'Complété',
    'fraud.documentsReceived': 'Documents reçus',
    'fraud.aiVerificationInProgress': 'Vérification IA en cours',
    'fraud.resultsUnderReview': 'Résultats en examen',
    'fraud.analysisFinalized': 'Analyse finalisée',
    'fraud.scan': 'Analyser',
    
    // FR — équivalents
    'fraud.doc1.name': 'Bulletin_Salaire_Mars_2024.pdf',
    'fraud.doc1.meta': '240 Ko • JUSTIFICATIF DE REVENUS',
    'fraud.doc2.name': 'Carte_Identite_Recto.jpg',
    'fraud.doc2.meta': '1,2 Mo • PIÈCE D\'IDENTITÉ',
    'fraud.doc3.name': 'Attestation_Employeur.pdf',
    'fraud.doc3.meta': '180 Ko • EMPLOI',

    'fraud.doc1.out0': 'Employeur confirmé. Montant du salaire cohérent avec les standards du marché.',
    'fraud.doc1.out1': 'Revenus vérifiés. Anomalie de mise en forme mineure détectée — probablement bénigne.',
    'fraud.doc1.out2': 'Bulletin authentique. NIF employeur recoupé avec succès.',
    'fraud.doc1.out3': 'Montant incohérent avec la taille déclarée de l\'entreprise. Vérification manuelle conseillée.',
    'fraud.doc1.out4': 'Possible falsification — métriques typographiques incohérentes sur le champ salaire.',
    'fraud.doc1.out5': 'Les métadonnées indiquent une modification 3 jours après la date d\'émission. Risque élevé.',

    'fraud.doc2.out0': 'Code MRZ valide. Biométrie du portrait validée.',
    'fraud.doc2.out1': 'Identité confirmée. Date d\'expiration dans la plage acceptable.',
    'fraud.doc2.out2': 'Scan basse résolution. Date d\'expiration dans 6 semaines.',
    'fraud.doc2.out3': 'Bande microimprimée floue — possible photocopie. Demander l\'original.',
    'fraud.doc2.out4': 'Incohérence détectée sur le cadrage du portrait. Artefacts lumineux en bordure.',
    'fraud.doc2.out5': 'Éléments de sécurité absents. Forte probabilité de falsification.',

    'fraud.doc3.out0': 'Dates d\'emploi confirmées. Signature numérique cryptographiquement valide.',
    'fraud.doc3.out1': 'Employeur vérifié dans le registre des entreprises. Termes du contrat cohérents.',
    'fraud.doc3.out2': 'Lettre de référence authentique. Coordonnées employeur vérifiées.',
    'fraud.doc3.out3': 'Signataire introuvable dans l\'annuaire de l\'entreprise. Possible tiers émetteur.',
    'fraud.doc3.out4': 'Écart de 4 mois non justifié. Divergence de date d\'entrée vs. CV.',
    'fraud.doc3.out5': 'Numéro SIRET inexistant dans le registre national. Document frauduleux.',

    'fraud.doc.income': 'Revenus',
    'fraud.doc.identity': 'Identité',
    'fraud.doc.employment': 'Emploi',
    'fraud.trustLabel.excellent': 'Excellent',
    'fraud.trustLabel.good': 'Bon',
    'fraud.trustLabel.moderate': 'Modéré',
    'fraud.trustLabel.poor': 'Faible',
    'fraud.trustLabel.highRisk': 'Risque Élevé',

    // How It Works
    'howItWorks.badge': 'Processus',
    'howItWorks.title1': 'De la candidature à l\'approbation',
    'howItWorks.title2': 'en quelques secondes.',
    'howItWorks.subtitle': 'Automatisez le travail lourd. Nous gérons les données, la vérification et le scoring pour que vous puissiez vous concentrer sur la décision.',
    'howItWorks.step1.title': 'Télécharger les Documents',
    'howItWorks.step1.desc': 'Les locataires téléchargent leur pièce d\'identité, bulletins de salaire et déclarations fiscales en quelques secondes. Fini les chaînes d\'emails ou PDFs perdus.',
    'howItWorks.step2.title': 'Analyse IA',
    'howItWorks.step2.desc': 'Notre moteur lit, vérifie et recoupe les données contre les modèles de fraude instantanément.',
    'howItWorks.step3.title': 'Obtenir les Résultats',
    'howItWorks.step3.desc': 'Recevez un score de risque complet, les alertes et le profil locataire vérifié prêt pour la décision.',
    'howItWorks.stat1.value': '< 30s',
    'howItWorks.stat1.label': 'Temps d\'Analyse',
    'howItWorks.stat2.value': '99.7%',
    'howItWorks.stat2.label': 'Détection de Fraude',
    'howItWorks.stat3.value': '45min',
    'howItWorks.stat3.label': 'Temps Économisé',
    'howItWorks.stat4.value': '0hr',
    'howItWorks.stat4.label': 'Lecture Manuelle de PDF',
    
    // Testimonial
    'testimonial.quote': 'Nous avons créé le CRM intelligent dont les agences avaient besoin.',
    'testimonial.subtext': 'Mais nous ne nous sommes pas arrêtés là. Chaque locataire vérifié mérite un passeport—une preuve portable de confiance qui le suit d\'un logement à l\'autre.',
    
    // Passport Demo
    'passport.badge': 'Démo Interactive en Direct',
    'passport.title1': 'Partageable.',
    'passport.title2': 'Crypté.',
    'passport.title3': 'Confidentialité d\'abord.',
    'passport.subtitle': 'Générez un lien public sécurisé que les agences peuvent consulter sans compte. Seul le statut vérifié est affiché — jamais vos données sensibles.',
    'passport.headerPrivate': 'Votre Tableau de Bord Passeport Privé',
    'passport.headerPublic': 'Vue Agence (Aucune Connexion Requise)',
    'passport.encrypted': 'Cryptage de Bout en Bout',
    'passport.fullPassport': 'Votre Passeport Complet',
    'passport.publicView': 'Vue Publique du Passeport',
    'passport.private': 'Privé',
    'passport.public': 'Public',
    'passport.verifiedSince': 'Vérifié depuis Mars 2024',
    'passport.identityStatus': 'Statut d\'Identité',
    'passport.verified': 'Vérifié ✓',
    'passport.fullName': 'Nom Complet',
    'passport.incomeBracket': 'Tranche de Revenus',
    'passport.exactSalary': 'Salaire Exact',
    'passport.employmentStatus': 'Statut d\'Emploi',
    'passport.employmentCDI': 'CDI (Permanent)',
    'passport.employerName': 'Nom de l\'Employeur',
    'passport.rentalHistory': 'Historique Locatif',
    'passport.rentalHistoryValue': '3+ ans, Aucun Problème',
    'passport.previousAddresses': 'Adresses Précédentes',
    'passport.trustScore': 'Score de Confiance',
    'passport.trustScoreValue': '98/100',
    'passport.fraudCheck': 'Vérification Fraude IA',
    'passport.fraudCheckPassed': 'Validé ✓',
    'passport.hidden': 'Masqué',
    'passport.shareTitle': 'Partagez Votre Passeport',
    'passport.whatAgenciesSee': 'Ce Que Voient les Agences',
    'passport.privacyProtected': 'Confidentialité Protégée',
    'passport.privacyDesc': 'Votre lien public n\'affiche que le statut vérifié, jamais les documents réels ou les données sensibles.',
    'passport.publiclyVisible': 'VISIBLE PUBLIQUEMENT',
    'passport.alwaysHidden': 'TOUJOURS MASQUÉ',
    'passport.publicItem1': 'Identité ✓',
    'passport.publicItem2': 'Tranche de Revenus',
    'passport.publicItem3': 'Type d\'Emploi',
    'passport.publicItem4': 'Historique Locatif',
    'passport.publicItem5': 'Score de Confiance',
    'passport.publicItem6': 'Vérification Fraude ✓',
    'passport.hiddenItem1': 'Nom Complet',
    'passport.hiddenItem2': 'Salaire Exact',
    'passport.hiddenItem3': 'Employeur',
    'passport.hiddenItem4': 'Adresses',
    'passport.hiddenItem5': 'Documents',
    'passport.generateLink': 'Générer un Lien Partageable',
    'passport.generating': 'Génération du lien crypté...',
    'passport.yourLink': 'Votre Lien Passeport',
    'passport.copy': 'Copier',
    'passport.copied': 'Copié',
    'passport.linkDescription': 'Toute personne avec ce lien peut voir votre statut vérifié — aucun compte nécessaire',
    'passport.tenantVerified': 'Locataire Vérifié',
    'passport.cryptoVerified': 'Ce passeport a été cryptographiquement vérifié par Luuzon IA.',
    'passport.quickSummary': 'Résumé Rapide',
    'passport.income': 'Revenus',
    'passport.employment': 'Emploi',
    'passport.history': 'Historique',
    'passport.fullDetailsAvailable': 'Détails Complets Disponibles',
    'passport.fullDetailsDesc': 'Demandez un accès complet via Luuzon pour voir les documents complets avec le consentement du locataire.',
    'passport.restartDemo': 'Redémarrer la Démo',
    'passport.feature1': 'Aucun Compte Requis',
    'passport.feature1Desc': 'Les agences consultent instantanément',
    'passport.feature2': 'Zéro Données Sensibles',
    'passport.feature2Desc': 'Seulement le statut de vérification',
    'passport.feature3': 'Preuve Cryptographique',
    'passport.feature3Desc': 'Vérification infalsifiable',
    
    // FAQ
    'faq.badge': 'FAQ',
    'faq.title': 'Des questions ? Nous avons les réponses.',
    'faq.q1': 'Comment l\'IA détecte-t-elle la fraude ?',
    'faq.a1': 'Notre IA analyse les documents pour détecter les incohérences, les anomalies de métadonnées, les irrégularités de police et fait des recoupements avec des modèles de fraude connus. Elle est formée sur des millions de documents vérifiés et frauduleux.',
    'faq.q2': 'Mes données sont-elles sécurisées ?',
    'faq.a2': 'Absolument. Nous utilisons un cryptage de niveau bancaire, une architecture à connaissance zéro et sommes conformes au RGPD. Vous contrôlez quelles données sont partagées et avec qui. Nous ne vendons jamais vos informations.',
    'faq.q3': 'Combien de temps prend la vérification ?',
    'faq.a3': 'La plupart des vérifications sont complétées en moins de 30 secondes. Les cas complexes nécessitant un examen manuel peuvent prendre jusqu\'à 24 heures, mais cela représente moins de 2% des candidatures.',
    'faq.q4': 'Puis-je l\'utiliser avec plusieurs agences ?',
    'faq.a4': 'Oui ! C\'est tout l\'intérêt. Construisez votre profil vérifié une fois, puis postulez auprès de n\'importe quelle agence ou propriété sur notre réseau en un seul clic. Votre score de confiance vous suit partout.',
    'faq.q5': 'Que se passe-t-il si un document est signalé ?',
    'faq.a5': 'Les documents signalés entrent en examen manuel par notre équipe de vérification. Vous serez informé et aurez l\'opportunité de soumettre des documents corrigés. Les faux positifs sont rares mais traités avec soin.',
    'faq.subtitle': 'Pour les Agences & Locataires',
    'faq.heading': 'Questions Fréquentes',
    'faq.question1': 'Comment Luuzon protège-t-il mes données personnelles ?',
    'faq.answer1': 'Nous utilisons un cryptage de niveau bancaire (AES-256) et nous respectons strictement le RGPD. Vos données sont cryptées au repos et en transit. Crucialement, les agences ne voient que votre statut vérifié sauf si vous leur accordez explicitement un accès complet.',
    'faq.question2': 'Que se passe-t-il en cas de fuite de données ?',
    'faq.answer2': 'Notre architecture décentralisée garantit que même dans l\'improbable cas d\'une fuite, les attaquants ne trouveraient que des fragments cryptés qui seraient inutiles sans votre clé privée.',
    'faq.question3': 'Combien coûte Luuzon pour les agences ?',
    'faq.answer3': 'Nous proposons des tarifs flexibles commençant par une tier gratuite d\'utilisation. Les plans d\'entreprise incluent un accès à l\'API et des remises pour les vérifications en masse.',
    'faq.question4': 'Luuzon est-il gratuit pour les locataires ?',
    'faq.answer4': 'Oui ! Les locataires peuvent créer un Passeport Vérifié gratuitement. Nous croyons que prouver votre crédibilité ne devrait pas vous coûter d\'argent.',
    'faq.question5': 'Comment fonctionne le processus de vérification par IA ?',
    'faq.answer5': 'Notre IA propriétaire analyse les métadonnées des documents, fait des recoupements des revenus avec les relevés bancaires et vérifie les bases de données de fraude globales instantanément.',
    'faq.question6': 'Combien de temps prend la vérification ?',
    'faq.answer6': 'Typiquement moins de 30 secondes. Dans des cas complexes rares, une revue manuelle peut prendre jusqu\'à 2 heures.',
    'faq.question7': 'Que se passe-t-il si l\'IA signale incorrectement mes documents ?',
    'faq.answer7': 'Vous pouvez demander une revue manuelle immédiatement. Notre équipe de conformité humaine réévaluera vos documents dans les 24 heures.',
    'faq.question8': 'Les agences peuvent-elles voir mes documents complets ?',
    'faq.answer8': 'Par défaut, non. Elles voient un statut \'Vérifié\'. Vous pouvez choisir de partager les fichiers réels si nécessaire pour la signature finale du bail.',
    'faq.moreQuestions': 'Plus de questions ?',
    'faq.contactUs': 'Contactez-nous',
    
    // Footer
    'footer.title': 'Vous n\'avez pas à faire ça seul',
    'footer.support': 'Support',
    'footer.manifesto': 'Lire notre Manifeste',
    'footer.contact': 'Contacter un fondateur',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.legal': 'Mentions Légales',
    'footer.copyright': '© Luuzon 2026',
    
    // Cookies
    'cookies.title': 'Nous respectons votre vie privée',
    'cookies.description': 'Nous utilisons des cookies pour améliorer votre expérience de navigation et analyser notre trafic. Vous pouvez choisir quels types de cookies vous autorisez.',
    'cookies.essential': 'Essentiels',
    'cookies.essentialDesc': 'Requis pour le fonctionnement du site',
    'cookies.analytics': 'Analytiques',
    'cookies.analyticsDesc': 'Nous aident à améliorer notre service',
    'cookies.marketing': 'Marketing',
    'cookies.marketingDesc': 'Utilisés pour la publicité ciblée',
    'cookies.acceptAll': 'Tout Accepter',
    'cookies.rejectAll': 'Tout Refuser',
    'cookies.configure': 'Configurer',
    'cookies.savePreferences': 'Enregistrer les Préférences',
    'cookies.backToMain': 'Retour',
    
    // Manifesto
    'manifesto.badge': 'Manifeste',
    'manifesto.hero.title1': 'Logement, Automatisé.',
    'manifesto.hero.title2': 'Vie, Simplifiée.',
    'manifesto.section1.number': '01 — Notre Philosophie',
    'manifesto.section1.title': 'La confiance est le fondement de chaque foyer',
    'manifesto.section1.p1': 'Le marché locatif est brisé. C\'est un enchevêtrement d\'inefficacités, de méfiance et de processus obsolètes qui frustrent les locataires et accablent les agences.',
    'manifesto.section1.p2': 'Nous croyons en un monde où la location est transparente, digne et sans friction. Où votre réputation vous suit. Où la confiance n\'est pas supposée—elle est vérifiée.',
    'manifesto.section1.p3': 'Il ne s\'agit pas seulement de technologie ; il s\'agit de restaurer l\'humanité dans le logement. Il s\'agit de construire des systèmes qui respectent à la fois les propriétaires et les locataires, créant un marché où l\'honnêteté est récompensée et la fraude est impossible.',
    'manifesto.section2.number': '02 — Pourquoi Maintenant',
    'manifesto.section2.title': 'Le moment du changement est arrivé',
    'manifesto.section2.p1': 'La fraude augmente. Les agences sont submergées. Les locataires passent des semaines à prouver leur crédibilité avec des montagnes de paperasse. Le système actuel gaspille temps, argent et confiance.',
    'manifesto.section2.p2': 'Pendant ce temps, l\'IA a atteint un point d\'inflexion. Ce qui nécessitait autrefois des armées d\'analystes peut maintenant être fait instantanément, avec précision et à grande échelle. Les outils existent. Le besoin est urgent. L\'opportunité est maintenant.',
    'manifesto.section2.p3': 'Nous sommes à l\'intersection de la crise et de la capacité—et c\'est là que la transformation se produit.',
    'manifesto.section3.number': '03 — Notre Solution',
    'manifesto.section3.title': 'Un écosystème intelligent pour une vie vérifiée',
    'manifesto.section3.p1': 'Nous construisons la norme institutionnelle pour la vérification de bail—une plateforme B2B2C neutre qui connecte des agences vérifiées avec des locataires honnêtes via une infrastructure de confiance alimentée par l\'IA.',
    'manifesto.section3.p2': 'Notre système vérifie instantanément les documents, détecte la fraude et construit des réputations locatives portables. Une candidature. Un profil. Possibilités infinies.',
    'manifesto.section3.p3': 'Les agences économisent du temps et réduisent les risques. Les locataires postulent plus rapidement et louent en toute confiance. Les propriétaires accueillent des résidents vérifiés. Tout le monde gagne quand le système fonctionne.',
    'manifesto.section4.number': '04 — Notre Vision',
    'manifesto.section4.title': 'Votre historique locatif comme passeport',
    'manifesto.section4.p1': 'Imaginez un monde où postuler pour un logement est aussi simple qu\'un seul clic. Où votre historique vérifié ouvre des portes au lieu de vous forcer à vous prouver encore et encore.',
    'manifesto.section4.p2': 'Nous envisageons un avenir où le logement est accessible, équitable et transparent. Où les données donnent du pouvoir plutôt qu\'elles n\'exploitent. Où la confidentialité et la vérification coexistent.',
    'manifesto.section4.p3': 'Nous ne construisons pas simplement un logiciel—nous repensons les fondations de notre façon de vivre. Rejoignez-nous pour faire fonctionner la location pour tous.',
    'manifesto.closing': 'Bienvenue dans le futur de la location',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const params = useParams();
  const navigate = useNavigate();
  const language = (params.lang as Language) || 'en';

  const setLanguage = (lang: Language) => {
    const currentPath = window.location.pathname;
    // Replace the language part of the URL
    const newPath = currentPath.replace(/^\/(en|fr)/, `/${lang}`);
    navigate(newPath);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}